using System.Threading.Tasks;

namespace DnDGameMaster.WebApp.Services.LLM
{
    public interface ILLMService
    {
        /// <summary>
        /// Get text generated by the LLM model for a given prompt
        /// </summary>
        Task<string> GetGeneratedTextAsync(string prompt);
        
        /// <summary>
        /// Get an image URL generated based on a prompt
        /// </summary>
        Task<string> GetGeneratedImageUrlAsync(string prompt);
    }
} 